
// Compare two lists of names
const list1 = ["apt. Siti Rahmawati M.Farm",
    "Fendi Yoga Wardana S.Si, M.Farm",
    "apt. Moh Firmansyah M.Farm",
    "Sartoyo S.Kes, S.Sos, M.Kes",
    "Widigdo Rekso Negoro S.Tr.Kep, M.H, M.Kes",
    "Apt. Mayang Aditya Ayuning Siwi S.Farm, M.Farm",
    "Ananda Umbar Putri Mulyani",
    "Indari S.Kep, Ners, M.Kep",
    "Kaslinda Nur Umifa S.Kep, Ners, M.Kep",
    "Eni Herawati S.E.",
    "Elvianto Wihatno S.Pd.,M.M.Kes",
    "Merisdawati MR S.Kep, Ners, M.Kep",
    "Ns. Aloysia Ispriantari S.Kep, M.Kep",
    "Anis Ansyori S.Psi, MMRS",
    "Dr. Juliati Koesrini A.Per.Pend.M.KPd",
    "Ikhwan Abdullah S.Psi, MM",
    "Anik Sri Purwanti SST, M.Keb",
    "Ina Indriati SST, M.Kes",
    "Angria Pradita S.FT, Physio, M.Biomed",
    "Apt. Rakhmadani Gadis Aprilianti S.Farm, M.Farm",
    "M. Syauqi Haris S.Kom, M.Kom",
    "Mochammad Anshori S.Kom, M.Kom",
    "Ahsanun Naseh Khudori S.Kom, M.Kom",
    "Ns. Rif'atul Fani S.Kep, M.Kep.",
    "Sulistiyah S.SI.T, M.Kes",
    "Tien Aminah S.Kep, Ners, M.Kep",
    "Lilik Afifah SE,M.Kes",
    "Ratih Tyas Widara S.Si, M.Si.",
    "Dion Kunto Adi Patria S.Kep,Ners, M.Kep",
    "Yuni Asri S.Kep, Ners, M.Kes, Ph.D.",
    "dr. Mayang Wulandari MM",
    "Maulana Arif Murtadho S.Kep, Ners, M.Kep",
    "Rosyidah Alfitri SST, MPH",
    "Amin Zakaria S.Kep,Ners, M.Kes",
    "Dr. Rifzul Maulina SST, M.Kes", ,
    "Apt. Nanang Ardianto S.Farm, M.Farm.Klin",
    "Amal Prihatono S.Ked, MM",
    "Ns. Bayu Budi Laksono S.Kep, M.Kep",
    "Dr. Apriyani Puji Hastuti S.Kep, Ners, M.Kep",
    "Agus Syukron Ma'ruf S.K.M, M.K.M",
    "Retno Dewi Prisusanti SST, M.P.H",
    "Achmad Fariz S.Ft, M.Fis, Ftr",
    "Bagus Dadang Prasetiyo S.T, M.T",
    "Apt. Beta Herilla Sekti S.Farm, M.Farm",
    "Raden Maria Veronika Widiatrilupi SST, M.Keb",
    "Achmad Jaelani Rusdi SST, M.Kes",
    "Hanim Mufarokhah S.Kep, Ners, M.Kep",
    "dr. Reko Priyonggo Sp. An",
    "Ns. Alfunnafi' Fahrul Rizzal S.Kep, Ners, Sp.Kep.J, M.Kep",
    "Hariati, S.Ak",
    "Prof.(H.C.) Arief Efendi S.Kes, SH(Adv), S.Kep, Ners, MM, M.Kes",
    "Apt. Agung Permata S.Farm, M.Farm",
    "Dr. Ardhiles Wahyu Kurniawan S.Kep, Ners, M.Kep",
    "Tut Rayani Aksohini Wijayanti SST, M.Keb",
    "Nila Widya Keswara SST, M.K.M",
    "Puspo Wardoyo S.Pd, MM",
    "Ns. Mokhtar Jamil S.Kep, M.Kep",
    "Chantika Mahadini S.Psi, M.Psi",
    "Risqy Siwi Pradini S.S.T, M.Kom",
    "Untung Slamet Suharyanto S.Kep.,Ners., M.Kes",
    "Dr. Widia Shofa Ilmiah S.ST, M.Kes",
    "Rani Safitri SST, M.Keb",
    "Agustina Risawati A.Md.",
    "Nurul halimah S.FT, Physio, M.Biomed",
    "Riki Ristanto S.Kep, Ners, M.Kep",
    "Musthika Wida Mashitah S.Kep, Ners, M.Biomed",
    "Ns. Heny Nurmayunita S.Kep, MMRS",
    "Reny Retnaningsih SST, M.Keb",
    "Wahyu Teja Kusuma S.Kom, M.Kom",
    "Ns. Shinta Wahyusari S.Kep, M.Kep ,Sp.Kep.Mat",
    "Anik Purwati SST, MM, M.Kes",
    "Dian Pitaloka Priasmoro S.Kep, Ners, M.Kep",
    "Ns. Ratna Roesardhyati S.Kep, M.Kep.",
    "Apt. Rudy Mardianto S.Si, M.M, M.Farm",
    "Fita Rusdian Ikawati SE, MM, M.Kes",
    "Apt. Aldesra Fitri S.Farm, M.Farm",
    "dr. Leny Chandra, MM"];
const list2 = ["apt. Siti Rahmawati M.Farm",
    "Apt. Rakhmadani Gadis Aprilianti S.Farm, M.Farm",
    "Dr. Rifzul Maulina SST, M.Kes",
    "Apt. Rudy Mardianto S.Si, M.M, M.Farm",
    "Eni Herawati S.E.",
    "Hariati, S.Ak",
    "Rani Safitri SST, M.Keb",
    "Elvianto Wihatno S.Pd.,M.M.Kes",
    "Ahsanun Naseh Khudori S.Kom, M.Kom",
    "Maulana Arif Murtadho S.Kep, Ners, M.Kep",
    "Agus Syukron Ma'ruf S.K.M, M.K.M",
    "dr. Leny Chandra, MM",
    "dr. Mayang Wulandari MM",
    "Angria Pradita S.FT, Physio, M.Biomed",
    "Untung Slamet Suharyanto S.Kep.,Ners., M.Kes",
    "Amin Zakaria S.Kep,Ners, M.Kes",
    "Nurul halimah S.FT, Physio, M.Biomed",
    "Fita Rusdian Ikawati SE, MM, M.Kes",
    "M. Syauqi Haris S.Kom, M.Kom",
    "Sulistiyah S.SI.T, M.Kes",
    "Yuni Asri S.Kep, Ners, M.Kes, Ph.D.",
    "Ns. Bayu Budi Laksono S.Kep, M.Kep",
    "Widigdo Rekso Negoro S.Tr.Kep, M.H, M.Kes",
    "Ns. Alfunnafi' Fahrul Rizzal S.Kep, Ners, Sp.Kep.J, M.Kep",
    "Wahyu Teja Kusuma S.Kom, M.Kom",
    "Ananda Umbar Putri Mulyani",
    "Rosyidah Alfitri SST, MPH",
    "Dion Kunto Adi Patria S.Kep,Ners, M.Kep",
    "Dr. Widia Shofa Ilmiah S.ST, M.Kes",
    "Apt. Aldesra Fitri S.Farm, M.Farm",
    "Lilik Afifah SE,M.Kes",
    "Chantika Mahadini S.Psi, M.Psi",
    "Mochammad Anshori S.Kom, M.Kom",
    "Retno Dewi Prisusanti SST, M.P.H",
    "Apt. Agung Permata S.Farm, M.Farm",
    "Merisdawati MR S.Kep, Ners, M.Kep",
    "Bagus Dadang Prasetiyo S.T, M.T",
    "Dr. Rachma Putri Kasimbara S.Pd, M.Pd",
    "Apt. Beta Herilla Sekti S.Farm, M.Farm",
    "Apt. Mayang Aditya Ayuning Siwi S.Farm, M.Farm",
    "Raden Maria Veronika Widiatrilupi SST, M.Keb",
    "Ns. Heny Nurmayunita S.Kep, MMRS",
    "Prof.(H.C.) Arief Efendi S.Kes, SH(Adv), S.Kep, Ners, MM, M.Kes",
    "Dian Pitaloka Priasmoro S.Kep, Ners, M.Kep",
    "Ratih Tyas Widara S.Si, M.Si.",
    "Hanim Mufarokhah S.Kep, Ners, M.Kep",
    "Dr. Ardhiles Wahyu Kurniawan S.Kep, Ners, M.Kep",
    "Musthika Wida Mashitah S.Kep, Ners, M.Biomed",
    "Tut Rayani Aksohini Wijayanti SST, M.Keb",
    "apt. Moh Firmansyah M.Farm",
    "Dr. Juliati Koesrini A.Per.Pend.M.KPd",
    "Ikhwan Abdullah S.Psi, MM",
    "Ns. Ratna Roesardhyati S.Kep, M.Kep.",
    "Dr. Apriyani Puji Hastuti S.Kep, Ners, M.Kep",
    "Indari S.Kep, Ners, M.Kep",
    "Agustina Risawati A.Md.",
    "Ns. Mokhtar Jamil S.Kep, M.Kep",
    "Risqy Siwi Pradini S.S.T, M.Kom",
    "Anik Sri Purwanti SST, M.Keb",
    "Achmad Jaelani Rusdi SST, M.Kes",
    "Kaslinda Nur Umifa S.Kep, Ners, M.Kep",
    "Anik Purwati SST, MM, M.Kes",
    "Ina Indriati SST, M.Kes",
    "Achmad Fariz S.Ft, M.Fis, Ftr",
    "dr. Reko Priyonggo Sp. An",
    "Anis Ansyori S.Psi, MMRS",
    "Riki Ristanto S.Kep, Ners, M.Kep",
    "Nila Widya Keswara SST, M.K.M",
    "Sartoyo S.Kes, S.Sos, M.Kes",
    "Ns. Rif'atul Fani S.Kep, M.Kep.",
    "Puspo Wardoyo S.Pd, MM",
    "Tien Aminah S.Kep, Ners, M.Kep",
    "Amal Prihatono S.Ked, MM",
    "Apt. Nanang Ardianto S.Farm, M.Farm.Klin",
    "Ns. Shinta Wahyusari S.Kep, M.Kep ,Sp.Kep.Mat",
    "Reny Retnaningsih SST, M.Keb",
    "Fendi Yoga Wardana S.Si, M.Farm",
    "Ns. Aloysia Ispriantari S.Kep, M.Kep",];

// Function to find names exclusive to one list
function findExclusiveNames() {
    // Names in list1 but not in list2
    const onlyInList1 = list1.filter(name => !list2.includes(name));

    // Names in list2 but not in list1
    const onlyInList2 = list2.filter(name => !list1.includes(name));

    console.log("Names only in list 1:", onlyInList1.length > 0 ? onlyInList1.join(", ") : "None");
    console.log("Names only in list 2:", onlyInList2.length > 0 ? onlyInList2.join(", ") : "None");
}

// Invoke the function to display results
findExclusiveNames();